import Head from 'next/head'
import { useRouter } from 'next/router';
import axios from 'axios'
import Cookies from 'js-cookie';
import FormLogin from '../components/Login/FormLogin';

export default function Home() {
  const router = useRouter()
  const onFinish = async (values) => {
    try {
      const { data } = await axios.post('http://localhost:8080/auth/login', values)
      const token = data.data.accessToken
      axios.defaults.headers.common = { 'Authorization': `Bearer ${token}` }
      Cookies.set('token', token)
      router.push('/user')
    } catch (error) {
      console.log(error)
      alert('datos incorrectos')
    }
  };
  return (
    <div className='h-screen flex items-center justify-center ' >
      <Head>
        <title>Ciudad Salud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FormLogin onFinish={onFinish} />
    </div>
  )
}
